version: '2'
services:
  app_server:
    build: .
    environment:
      - SETTINGS_DIR=/app/settings/nanostorm
    volumes:
      - ~/.nanostorm/logs/nanostorm:/app/logs
      - ~/.nanostorm/run:/app/run
  http_proxy:
    image: nginx
    volumes:
      - ~/.nanostorm/logs/nginx:/var/log/nginx
      - ./settings/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - '80:80'
    environment:
     - NGINX_HOST=nanostorm.vault13.org
     - NGINX_PORT=80
    volumes_from:
    - app_server
