version: '3'
services:
  app_server:
    build: .
    environment:
    - SETTINGS_DIR=/app/settings
    volumes:
      # - ~/.nanostorm/settings/nanostorm:/app/settings
      - ~/.nanostorm/logs:/app/logs
      - app_sockets:/tmp/nanostorm
    links:
      - nano_node
  http_proxy:
    image: nginx
    environment:
    - NGINX_HOST=domain.com
    - NGINX_PORT=80
    volumes:
      #- nginx_config:/etc/nginx/nginx.conf
      - app_sockets:/tmp/nanostorm
    ports:
     - "80:80"
  nano_node:
    image: nanocurrency/nano
    ports:
      - "7075:7075"
      - "7076:7076"
    volumes:
      - ~/.nanostorm/node:/root/RaiBlocks
volumes:
    app_sockets:
